### ISSUE TITLE
Fluent Typer does not work if there is a word directly after it.

### ISSUE THREAD

**Issue by Jorc0** [bartekplus/FluentTyper#79] opened 2024-01-04 09:28 UTC
I use it for work, but it has small, improvable flaws
https://github.com/bartekplus/FluentTyper/assets/48130077/4a42b6ea-354d-4f1a-8316-922e36abecf5

**Comment by Jorc0** [comment] 2024-01-04 09:42
I also noted it wont load sometimes as you can see at the beginning of the video

**Comment by bartekplus** [comment] 2024-01-04 09:42
@Jorc0 Please provide full example to reproduce the issue. It work as expected on most site e.g.: 
[Screencast from 04.01.2024 10:39:08.webm](https://github.com/bartekplus/FluentTyper/assets/7108667/e28ee7e7-115c-4cf2-8e3b-450f2657b943)

It must be something specific to your page/setup/env. It won't be fixed without your input.

**Comment by Jorc0** [comment] 2024-01-04 09:50
https://github.com/bartekplus/FluentTyper/assets/48130077/3cd56335-927d-4eb3-a42a-1ebfc9008468

**Comment by Jorc0** [comment] 2024-01-04 09:53
This is my setup so you can further understand 
![image](https://github.com/bartekplus/FluentTyper/assets/48130077/45d25246-e13d-4cbb-8e66-735b3f337d8c)

**Comment by bartekplus** [comment] 2024-01-04 09:57
I'm not sure what do you mean. Text expander is designed to work only if whole world match. The editing in middle of word do not match whole word(letters after carret also matters/This is done by design and it won't be changed. This is done to allow editing and fixing typos in middle of words.

**Comment by Jorc0** [comment] 2024-01-04 10:00
But its not middle word, i want to add a word using expander in front of the current word, its not possible?
In that case i want to add the expander op -> operadora: in front of "says something" so i put the cursor in front of the word "says" so it can automatically add the expander option "op -> operadora: "

**Comment by bartekplus** [comment] 2024-01-04 10:02
Yes it's middle of the word. It's not possible by design.

Adding letter without space before any word makes it middle of a word.

**Comment by bartekplus** [comment] 2024-01-04 16:35
The feature works as intended, and I do not plan to change it.

@Jorc0 If you have the knowledge and are willing to do it, feel free to work on it and open a pull request.

**Closed by bartekplus** 2024-01-04 16:35 UTC
Labels: bug
